{
 "title": "OpenFaaS",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Function rate",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate ( gateway_function_invocation_total [20s])",
     "legendFormat": "{{ function_name }} {{code}}"
    }
   ]
  },
  {
   "title": "Replica scaling",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "gateway_service_count", "legendFormat": "{{function_name}} " }
   ]
  },
  {
   "title": "Execution duration (s)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(rate(gateway_functions_seconds_sum[20s]) / rate(gateway_functions_seconds_count[20s]))",
     "legendFormat": "{{function_name}} "
    }
   ]
  },
  {
   "title": "Total requests - 200 OK",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "scalar( sum( gateway_function_invocation_total {  code=\"200\"} ))"
    }
   ]
  }
 ]
}